---
name: Requeue stale scans

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 12 * * 2,4,6'

  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod

jobs:
  enqueue:
    runs-on: ubuntu-latest

    steps:
      - name: run requeue-stale-scans cli job in chosen space
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space || 'prod' }}
          cf_command: run-task site-scanner-consumer
            -c "node dist/apps/cli/main.js requeue-stale-scans"
            -k 2G -m 2G
            --name github-action-requeue-stale-scans-${{ github.run_id }}
