---
name: Snyk Scan

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04 # v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Check to see if the SARIF a was generated
        id: sarif_file_exists
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
        with:
          files: 'snyk.sarif'

      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@b8bb9f28b8d3f992092362369c57161b755dea45 # v4.45.0
        if: steps.sarif_file_exists.outputs.files_exists == 'true'
        with:
          sarif_file: snyk.sarif
